version: '3.8'

services:
  onetimeshare:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - APP_BASE_URL=${APP_BASE_URL:-http://localhost:8080}
      - STORAGE_ROOT=/app/storage
      - SQLITE_CONN_STRING=Data Source=/app/App_Data/app.db
      - MAX_UPLOAD_BYTES=${MAX_UPLOAD_BYTES:-104857600}
      - FILE_RETENTION_DAYS=${FILE_RETENTION_DAYS:-30}
      - CLEANUP_INTERVAL_MINUTES=${CLEANUP_INTERVAL_MINUTES:-1440}
      - COOKIE_SECURE=${COOKIE_SECURE:-true}
      - LOG_LEVEL=${LOG_LEVEL:-Information}
    volumes:
      - storage_data:/app/storage
      - db_data:/app/App_Data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  storage_data:
    driver: local
  db_data:
    driver: local