version: '3.8'

services:
  onetimeshare:
    build: 
      context: .
      target: build
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - APP_BASE_URL=${APP_BASE_URL:-http://localhost:5000}
      - STORAGE_ROOT=/app/storage
      - SQLITE_CONN_STRING=Data Source=/app/App_Data/app.db
      - MAX_UPLOAD_BYTES=${MAX_UPLOAD_BYTES:-104857600}
      - FILE_RETENTION_DAYS=${FILE_RETENTION_DAYS:-30}
      - CLEANUP_INTERVAL_MINUTES=${CLEANUP_INTERVAL_MINUTES:-60}
      - COOKIE_SECURE=false
      - LOG_LEVEL=Debug
    volumes:
      - ./src:/app/src
      - ./storage:/app/storage
      - ./App_Data:/app/App_Data
    command: ["dotnet", "watch", "run", "--project", "/app/src/OneTimeShare.Web"]
    restart: unless-stopped